#!/bin/sh
set -e

CONFIG="${MURID_CONFIG:-/app/murid.toml}"

# ── Auto-generate keys if missing (first run) ──
if [ "$1" = "run" ] || [ "$1" = "stake" ] || [ "$1" = "status" ]; then
    # Generate EVM key if not present
    if [ ! -f /app/keys/node.key ]; then
        echo "==> No EVM key found, generating..."
        murid wallet new -out /app/keys/node.key
        echo ""
    fi

    # Generate ZK secret key if not present
    if [ ! -f /app/keys/secret.key ]; then
        echo "==> No ZK secret key found, generating..."
        murid keygen -out /app/keys/secret.key
        echo ""
    fi

    # Download prover keys if not present
    if [ ! -f /app/keys/poi_prover.key ]; then
        echo "==> Prover keys not found, downloading (~200 MB)..."
        murid download-keys -out /app/keys
        echo ""
    fi

    # Generate config if not present
    if [ ! -f "$CONFIG" ]; then
        echo "==> No config found, generating default at $CONFIG"
        cat > "$CONFIG" <<TOML
# murid — auto-generated by docker-entrypoint.sh

[chain]
rpc_url = "${MURID_RPC_URL:-http://avago:9650/ext/bc/2qyiuZtqxCmwRosTYFBsoyTSsupLwsvvFPh9K2inL82Sd8m8Yf/rpc}"
chain_id = ${MURID_CHAIN_ID:-44946}
market_address = "${MURID_MARKET_ADDRESS:-0xf269a406a2be691cb038203ff6bdcfc5e13acdc6}"
staking_address = ""
gas_limit = ${MURID_GAS_LIMIT:-500000}
max_gas_price = ${MURID_MAX_GAS_PRICE:-100}
gas_priority = ${MURID_GAS_PRIORITY:-2}
gas_escalation = ${MURID_GAS_ESCALATION:-1.25}
max_retries = ${MURID_MAX_RETRIES:-3}
confirmation_blocks = ${MURID_CONFIRMATION_BLOCKS:-1}
listen_mode = "${MURID_LISTEN_MODE:-poll}"
ws_url = "${MURID_WS_URL:-}"

[ipfs]
api_url = "${MURID_IPFS_URL:-http://ipfs:5001}"
timeout = "${MURID_IPFS_TIMEOUT:-30s}"
pin_files = ${MURID_PIN_FILES:-true}

[node]
private_key_path = "/app/keys/node.key"
data_dir = "/app/data"
keys_dir = "/app/keys"
secret_key_path = "/app/keys/secret.key"

[storage]
max_capacity = ${MURID_MAX_CAPACITY:-1048576}
min_price = ${MURID_MIN_PRICE:-1000}

[auto_execute]
enabled = ${MURID_AUTO_EXECUTE:-true}
poll_interval = "${MURID_ORDER_POLL:-30s}"
max_orders_to_fill = ${MURID_MAX_ORDERS:-5}

[challenge]
poll_interval = "${MURID_CHALLENGE_POLL:-4s}"
safety_margin = ${MURID_SAFETY_MARGIN:-10}

[log]
level = "${MURID_LOG_LEVEL:-info}"
pretty = ${MURID_LOG_PRETTY:-true}
TOML
        echo ""
    fi
fi

# Pass through to murid with the config flag
case "$1" in
    run|status|stake|unstake|increase-capacity|decrease-capacity)
        CMD="$1"
        shift
        exec murid "$CMD" -config "$CONFIG" "$@"
        ;;
    *)
        exec murid "$@"
        ;;
esac
